export const ACHIEVEMENT_LIST = [
    // Workout Achievements
    {
        id: "first_workout",
        name: "💪 Primeira Sessão",
        description: "Complete seu primeiro treino",
        icon: "💪",
        xpReward: 50,
        rarity: "common",
        category: "workout",
        requirement: { type: "workouts", value: 1 },
    },
    {
        id: "workout_warrior",
        name: "⚔️ Guerreiro do Treino",
        description: "Complete 10 treinos",
        icon: "⚔️",
        xpReward: 200,
        rarity: "uncommon",
        category: "workout",
        requirement: { type: "workouts", value: 10 },
    },
    {
        id: "workout_centurion",
        name: "🏛️ Centurião",
        description: "Complete 100 treinos",
        icon: "🏛️",
        xpReward: 1000,
        rarity: "rare",
        category: "workout",
        requirement: { type: "workouts", value: 100 },
    },
    {
        id: "workout_legend",
        name: "⭐ Lenda dos Treinos",
        description: "Complete 1000 treinos",
        icon: "⭐",
        xpReward: 10000,
        rarity: "legendary",
        category: "workout",
        requirement: { type: "workouts", value: 1000 },
    },

    // Streak Achievements
    {
        id: "week_warrior",
        name: "🔥 Guerreiro Semanal",
        description: "Mantenha uma streak de 7 dias",
        icon: "🔥",
        xpReward: 200,
        rarity: "uncommon",
        category: "streak",
        requirement: { type: "streak", value: 7 },
    },
    {
        id: "month_master",
        name: "🏆 Mestre do Mês",
        description: "Mantenha uma streak de 30 dias",
        icon: "🏆",
        xpReward: 1000,
        rarity: "rare",
        category: "streak",
        requirement: { type: "streak", value: 30 },
    },
    {
        id: "year_legend",
        name: "👑 Lenda do Ano",
        description: "Mantenha uma streak de 365 dias",
        icon: "👑",
        xpReward: 10000,
        rarity: "legendary",
        category: "streak",
        requirement: { type: "streak", value: 365 },
    },

    // Perfect Workout Achievements
    {
        id: "perfect_10",
        name: "💎 Perfeito 10",
        description: "Complete 10 treinos perfeitos (100%)",
        icon: "💎",
        xpReward: 500,
        rarity: "rare",
        category: "workout",
        requirement: { type: "perfect_workouts", value: 10 },
    },
    {
        id: "perfect_100",
        name: "✨ Perfeição Absoluta",
        description: "Complete 100 treinos perfeitos",
        icon: "✨",
        xpReward: 5000,
        rarity: "legendary",
        category: "workout",
        requirement: { type: "perfect_workouts", value: 100 },
    },

    // Challenge Achievements
    {
        id: "challenge_beginner",
        name: "🎯 Desafiante Iniciante",
        description: "Complete 5 desafios",
        icon: "🎯",
        xpReward: 250,
        rarity: "uncommon",
        category: "challenge",
        requirement: { type: "challenges", value: 5 },
    },
    {
        id: "challenge_master",
        name: "🏅 Mestre dos Desafios",
        description: "Complete 50 desafios",
        icon: "🏅",
        xpReward: 2000,
        rarity: "epic",
        category: "challenge",
        requirement: { type: "challenges", value: 50 },
    },

    // Social Achievements
    {
        id: "helpful_hero",
        name: "🤝 Herói Prestativo",
        description: "Ajude 10 usuários",
        icon: "🤝",
        xpReward: 300,
        rarity: "uncommon",
        category: "social",
        requirement: { type: "help_users", value: 10 },
    },
    {
        id: "community_leader",
        name: "👑 Líder da Comunidade",
        description: "Alcance 1000 pontos sociais",
        icon: "👑",
        xpReward: 2000,
        rarity: "legendary",
        category: "social",
        requirement: { type: "social_score", value: 1000 },
    },

    // Level Achievements
    {
        id: "level_10",
        name: "🔟 Nível 10",
        description: "Alcance o nível 10",
        icon: "🔟",
        xpReward: 500,
        rarity: "uncommon",
        category: "legend",
        requirement: { type: "level", value: 10 },
    },
    {
        id: "level_50",
        name: "5️⃣0️⃣ Nível 50",
        description: "Alcance o nível 50",
        icon: "5️⃣0️⃣",
        xpReward: 5000,
        rarity: "epic",
        category: "legend",
        requirement: { type: "level", value: 50 },
    },
    {
        id: "level_100",
        name: "💯 Centurião Lendário",
        description: "Alcance o nível 100",
        icon: "💯",
        xpReward: 20000,
        rarity: "legendary",
        category: "legend",
        requirement: { type: "level", value: 100 },
    },
];
