import { sql } from "drizzle-orm";
import { pgTable, text, varchar, integer, timestamp, boolean, real, jsonb, date } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Users table
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  age: integer("age"),
  sex: text("sex"),
  height: integer("height"),
  weight: real("weight"),
  experience: text("experience"),
  goal: text("goal"),
  daysPerWeek: integer("days_per_week"),
  sessionMinutes: integer("session_minutes"),
  location: text("location"),
  equipment: text("equipment").array(),
  injuries: text("injuries"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// User stats (XP, level, streaks, etc.)
export const userStats = pgTable("user_stats", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  xp: integer("xp").default(0).notNull(),
  level: integer("level").default(1).notNull(),
  streak: integer("streak").default(0).notNull(),
  longestStreak: integer("longest_streak").default(0).notNull(),
  streakFreezes: integer("streak_freezes").default(1).notNull(),
  lastWorkoutDate: date("last_workout_date"),
  totalWorkouts: integer("total_workouts").default(0).notNull(),
  leagueTier: text("league_tier").default("Bronze").notNull(),
  weeklyXP: integer("weekly_xp").default(0).notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Workout plans (generated by AI)
export const workoutPlans = pgTable("workout_plans", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  description: text("description"),
  weekCount: integer("week_count").default(4).notNull(),
  active: boolean("active").default(true).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Individual workouts within a plan
export const workouts = pgTable("workouts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  planId: varchar("plan_id").notNull().references(() => workoutPlans.id, { onDelete: "cascade" }),
  weekNumber: integer("week_number").notNull(),
  dayNumber: integer("day_number").notNull(),
  focus: text("focus").notNull(),
  duration: integer("duration").notNull(),
  scheduledDate: date("scheduled_date"),
  completed: boolean("completed").default(false).notNull(),
  completedAt: timestamp("completed_at"),
});

// Exercises in each workout
export const workoutExercises = pgTable("workout_exercises", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  workoutId: varchar("workout_id").notNull().references(() => workouts.id, { onDelete: "cascade" }),
  exerciseName: text("exercise_name").notNull(),
  sets: integer("sets").notNull(),
  reps: text("reps").notNull(),
  rest: integer("rest").notNull(),
  notes: text("notes"),
  orderIndex: integer("order_index").notNull(),
});

// Logged exercise sets (user performance)
export const exerciseLogs = pgTable("exercise_logs", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  workoutExerciseId: varchar("workout_exercise_id").notNull().references(() => workoutExercises.id, { onDelete: "cascade" }),
  setNumber: integer("set_number").notNull(),
  load: real("load"),
  reps: integer("reps"),
  rpe: integer("rpe"),
  completed: boolean("completed").default(false).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Daily check-ins
export const checkIns = pgTable("check_ins", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  date: date("date").notNull(),
  mood: integer("mood").notNull(),
  sleep: integer("sleep").notNull(),
  pain: integer("pain").notNull(),
  fatigue: integer("fatigue").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Personal records
export const personalRecords = pgTable("personal_records", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  exerciseName: text("exercise_name").notNull(),
  load: real("load").notNull(),
  reps: integer("reps"),
  achievedAt: timestamp("achieved_at").defaultNow().notNull(),
});

// Badges/achievements
export const userBadges = pgTable("user_badges", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  badgeId: text("badge_id").notNull(),
  earnedAt: timestamp("earned_at").defaultNow().notNull(),
});

// Missions
export const missions = pgTable("missions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  type: text("type").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  target: integer("target").notNull(),
  progress: integer("progress").default(0).notNull(),
  completed: boolean("completed").default(false).notNull(),
  date: date("date").notNull(),
  xpReward: integer("xp_reward").notNull(),
});

// Zod schemas
export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true });
export const insertUserStatsSchema = createInsertSchema(userStats).omit({ id: true, updatedAt: true });
export const insertWorkoutPlanSchema = createInsertSchema(workoutPlans).omit({ id: true, createdAt: true });
export const insertWorkoutSchema = createInsertSchema(workouts).omit({ id: true });
export const insertWorkoutExerciseSchema = createInsertSchema(workoutExercises).omit({ id: true });
export const insertExerciseLogSchema = createInsertSchema(exerciseLogs).omit({ id: true, createdAt: true });
export const insertCheckInSchema = createInsertSchema(checkIns).omit({ id: true, createdAt: true });
export const insertPersonalRecordSchema = createInsertSchema(personalRecords).omit({ id: true, achievedAt: true });
export const insertUserBadgeSchema = createInsertSchema(userBadges).omit({ id: true, earnedAt: true });
export const insertMissionSchema = createInsertSchema(missions).omit({ id: true });

// Types
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type UserStats = typeof userStats.$inferSelect;
export type WorkoutPlan = typeof workoutPlans.$inferSelect;
export type Workout = typeof workouts.$inferSelect;
export type WorkoutExercise = typeof workoutExercises.$inferSelect;
export type ExerciseLog = typeof exerciseLogs.$inferSelect;
export type CheckIn = typeof checkIns.$inferSelect;
export type PersonalRecord = typeof personalRecords.$inferSelect;
export type UserBadge = typeof userBadges.$inferSelect;
export type Mission = typeof missions.$inferSelect;
